"""
3D tetrahedral lattice: perpendicular R/L BC helix chains crossing at single sites.

Each site (tetrahedron) sits at the intersection of exactly one R-chain and one
L-chain. The R-chain and L-chain pass through perpendicular pairs of faces and
have perpendicular helix axes.

Construction rule:
- R-chain vertex sequence: [v_0, v_1, v_2, v_3, v_4, ...]
  Tet n = {v_n, v_{n+1}, v_{n+2}, v_{n+3}}, always drops v_n (oldest).
- L-chain at R-chain tet n: vertex sequence starts with the permutation
  [v_{n+1}, v_{n+3}, v_n, v_{n+2}] of the same 4 vertices, then extends
  as its own BC helix (drop oldest, append new).
- The L-chain immediately diverges to different tetrahedra, sharing only
  the starting tet with the R-chain.
"""

import numpy as np
from src.helix_geometry import vertex, centroid, THETA_BC, R_VERTEX, H_VERTEX


def find_fourth_vertex(v0, v1, v2, v_old):
    """Given 3 vertices of a regular tet and the old 4th vertex,
    find the new 4th vertex (reflection through the face plane)."""
    return 2 * (v0 + v1 + v2) / 3 - v_old


# The permutation that generates the perpendicular L-chain from an R-chain
L_PERM = [1, 3, 0, 2]


class Chain:
    """A BC helix chain defined by its vertex sequence."""

    def __init__(self, initial_vertices, chain_id, is_r):
        """
        Parameters
        ----------
        initial_vertices : list of 4 ndarray(3,)
            The 4 vertices of the starting tetrahedron, in sequence order.
            Vertex 0 will be dropped first.
        chain_id : int
        is_r : bool
        """
        self.chain_id = chain_id
        self.is_r = is_r
        # Vertex sequence: indices 0..3 are the initial tet,
        # index 4+ are generated by extending forward.
        # Negative indices for backward extension.
        self._vertices = dict(enumerate(initial_vertices))
        self._min_idx = 0
        self._max_idx = 3

    def vertex(self, k):
        """Get vertex k, extending the sequence if needed."""
        while k > self._max_idx:
            self._extend_forward()
        while k < self._min_idx:
            self._extend_backward()
        return self._vertices[k]

    def _extend_forward(self):
        k = self._max_idx + 1
        v_old = self._vertices[k - 4]
        v_keep = [self._vertices[k - 3], self._vertices[k - 2], self._vertices[k - 1]]
        self._vertices[k] = find_fourth_vertex(v_keep[0], v_keep[1], v_keep[2], v_old)
        self._max_idx = k

    def _extend_backward(self):
        k = self._min_idx - 1
        v_old = self._vertices[k + 4]
        v_keep = [self._vertices[k + 1], self._vertices[k + 2], self._vertices[k + 3]]
        self._vertices[k] = find_fourth_vertex(v_keep[0], v_keep[1], v_keep[2], v_old)
        self._min_idx = k

    def tet_vertices(self, n):
        """Vertices of tetrahedron n: {v_n, v_{n+1}, v_{n+2}, v_{n+3}}."""
        return [self.vertex(n + k) for k in range(4)]

    def tet_centroid(self, n):
        """Centroid of tetrahedron n."""
        return np.mean(self.tet_vertices(n), axis=0)

    def exit_direction(self, n):
        """Unit exit direction at tet n (toward dropped vertex v_n)."""
        c = self.tet_centroid(n)
        d = self.vertex(n) - c
        return d / np.linalg.norm(d)

    def axis(self, n_steps=None):
        """Compute helix axis from the chain's vertex positions.

        The BC helix axis in the formula frame is (0,0,1). We find the
        rotation R mapping the reference tet to this chain's initial tet
        via the isotropy relation R = (3/4) Σ d_chain[k] ⊗ d_ref[k].
        """
        # Reference tet vertex directions in formula frame
        t_sign = 1 if self.is_r else -1
        ref_verts = []
        for k in range(4):
            angle = k * THETA_BC * t_sign
            ref_verts.append(np.array([
                R_VERTEX * np.cos(angle),
                R_VERTEX * np.sin(angle),
                k * H_VERTEX,
            ]))
        ref_c = np.mean(ref_verts, axis=0)
        ref_dirs = [(v - ref_c) / np.linalg.norm(v - ref_c) for v in ref_verts]

        init_verts = [self._vertices[k] for k in range(4)]
        init_c = np.mean(init_verts, axis=0)
        init_dirs = [(v - init_c) / np.linalg.norm(v - init_c) for v in init_verts]

        # R = (3/4) Σ init_dirs[k] ⊗ ref_dirs[k] (exact for tet isotropy)
        H = np.zeros((3, 3))
        for k in range(4):
            H += np.outer(init_dirs[k], ref_dirs[k])
        R = 0.75 * H

        # Helix axis is (0,0,1) in the formula frame
        return R @ np.array([0, 0, 1])


class Site:
    """A site at the crossing of one R-chain and one L-chain."""

    def __init__(self, site_id, pos, r_chain_id, r_idx, l_chain_id, l_idx):
        self.site_id = site_id
        self.pos = pos
        self.r_chain_id = r_chain_id
        self.r_idx = r_idx
        self.l_chain_id = l_chain_id
        self.l_idx = l_idx


class Lattice3D:
    """3D lattice of perpendicular R/L BC helix chains."""

    def __init__(self):
        self.sites = []
        self.chains = []
        self._pos_index = {}  # rounded pos tuple → site_id

    def _pos_key(self, pos, tol=1e-6):
        return tuple(np.round(pos / tol).astype(int))

    def find_site_near(self, pos, tol=1e-4):
        """Find existing site near pos, or return None."""
        key = self._pos_key(pos)
        # Check nearby keys
        for dk in range(-2, 3):
            for dj in range(-2, 3):
                for di in range(-2, 3):
                    k = (key[0]+di, key[1]+dj, key[2]+dk)
                    if k in self._pos_index:
                        sid = self._pos_index[k]
                        if np.linalg.norm(self.sites[sid].pos - pos) < tol:
                            return sid
        return None

    def add_site(self, pos, r_chain_id=-1, r_idx=-1, l_chain_id=-1, l_idx=-1):
        sid = len(self.sites)
        site = Site(sid, pos, r_chain_id, r_idx, l_chain_id, l_idx)
        self.sites.append(site)
        self._pos_index[self._pos_key(pos)] = sid
        return sid

    def add_chain(self, initial_vertices, is_r):
        cid = len(self.chains)
        chain = Chain(initial_vertices, cid, is_r)
        self.chains.append(chain)
        return cid

    def build_from_seed(self, r_extent=10, l_extent=5, depth=1):
        """
        Build lattice starting from a seed R-chain.

        Parameters
        ----------
        r_extent : int
            Number of tetrahedra in the seed R-chain (in each direction).
        l_extent : int
            Number of tetrahedra to extend each L-chain (in each direction).
        depth : int
            Number of layers of cross-chains to build.
        """
        # Layer 0: seed R-chain from analytic formula
        seed_verts = [vertex(k) for k in range(4)]
        seed_r = self.add_chain(seed_verts, is_r=True)

        # Create sites along seed R-chain
        for n in range(-r_extent, r_extent + 1):
            pos = self.chains[seed_r].tet_centroid(n)
            sid = self.find_site_near(pos)
            if sid is None:
                sid = self.add_site(pos, r_chain_id=seed_r, r_idx=n)
            else:
                self.sites[sid].r_chain_id = seed_r
                self.sites[sid].r_idx = n

        # Create L-chains at each seed R-chain site
        for site in list(self.sites):
            if site.l_chain_id >= 0:
                continue  # already has L-chain
            if site.r_chain_id < 0:
                continue

            r_chain = self.chains[site.r_chain_id]
            r_n = site.r_idx
            r_verts = r_chain.tet_vertices(r_n)

            # L-chain vertex sequence: permute by L_PERM
            l_verts = [r_verts[L_PERM[k]] for k in range(4)]
            l_cid = self.add_chain(l_verts, is_r=False)

            # The crossing site is at L-chain tet 0
            site.l_chain_id = l_cid
            site.l_idx = 0

            # Extend L-chain
            l_chain = self.chains[l_cid]
            for ln in range(-l_extent, l_extent + 1):
                if ln == 0:
                    continue  # already created (the crossing site)
                pos = l_chain.tet_centroid(ln)
                sid = self.find_site_near(pos)
                if sid is None:
                    sid = self.add_site(pos, l_chain_id=l_cid, l_idx=ln)
                else:
                    if self.sites[sid].l_chain_id < 0:
                        self.sites[sid].l_chain_id = l_cid
                        self.sites[sid].l_idx = ln

        # Build R-chains at L-chain sites that don't have one
        if depth > 0:
            for site in list(self.sites):
                if site.r_chain_id >= 0:
                    continue
                if site.l_chain_id < 0:
                    continue

                l_chain = self.chains[site.l_chain_id]
                l_n = site.l_idx
                l_verts = l_chain.tet_vertices(l_n)

                # R-chain at an L-chain site: apply INVERSE permutation
                # L_PERM = [1,3,0,2]. Inverse: [2,0,3,1]
                inv_perm = [2, 0, 3, 1]
                r_verts = [l_verts[inv_perm[k]] for k in range(4)]
                r_cid = self.add_chain(r_verts, is_r=True)

                site.r_chain_id = r_cid
                site.r_idx = 0

                # Extend R-chain
                r_chain = self.chains[r_cid]
                for rn in range(-r_extent, r_extent + 1):
                    if rn == 0:
                        continue
                    pos = r_chain.tet_centroid(rn)
                    sid = self.find_site_near(pos)
                    if sid is None:
                        sid = self.add_site(pos, r_chain_id=r_cid, r_idx=rn)
                    else:
                        if self.sites[sid].r_chain_id < 0:
                            self.sites[sid].r_chain_id = r_cid
                            self.sites[sid].r_idx = rn


def verify_lattice(lat):
    """Run consistency checks on the lattice."""
    print(f"Lattice: {len(lat.sites)} sites, {len(lat.chains)} chains")

    n_r = sum(1 for c in lat.chains if c.is_r)
    n_l = sum(1 for c in lat.chains if not c.is_r)
    print(f"  R-chains: {n_r}, L-chains: {n_l}")

    # Check perpendicularity of R/L axes at crossing sites
    dots = []
    for site in lat.sites:
        if site.r_chain_id >= 0 and site.l_chain_id >= 0:
            r_chain = lat.chains[site.r_chain_id]
            l_chain = lat.chains[site.l_chain_id]
            ax_r = r_chain.axis()
            ax_l = l_chain.axis()
            dots.append(abs(np.dot(ax_r, ax_l)))

    if dots:
        print(f"  R·L axis dots at crossings: max={max(dots):.6f}, mean={np.mean(dots):.6f}")
        print(f"  All perpendicular (|dot| < 0.01): {all(d < 0.01 for d in dots)}")

    # Check that R and L chains share at most 1 site
    for i, ci in enumerate(lat.chains):
        for j, cj in enumerate(lat.chains):
            if j <= i:
                continue
            if ci.is_r == cj.is_r:
                continue  # same chirality, skip
            shared = 0
            for site in lat.sites:
                on_i = (site.r_chain_id == i and ci.is_r) or (site.l_chain_id == i and not ci.is_r)
                on_j = (site.r_chain_id == j and cj.is_r) or (site.l_chain_id == j and not cj.is_r)
                if on_i and on_j:
                    shared += 1
            if shared > 1:
                print(f"  WARNING: chains {i} and {j} share {shared} sites!")

    # Check sites with both R and L chain
    both = sum(1 for s in lat.sites if s.r_chain_id >= 0 and s.l_chain_id >= 0)
    r_only = sum(1 for s in lat.sites if s.r_chain_id >= 0 and s.l_chain_id < 0)
    l_only = sum(1 for s in lat.sites if s.r_chain_id < 0 and s.l_chain_id >= 0)
    print(f"  Sites with both R+L: {both}, R-only: {r_only}, L-only: {l_only}")


if __name__ == '__main__':
    lat = Lattice3D()
    lat.build_from_seed(r_extent=5, l_extent=3, depth=1)
    verify_lattice(lat)
